main: net.initialposition.minecraftlives.MinecraftLives
name: MinecraftLives
version: 1.1.2
description: Implements a life system into Minecraft. Running out of lives bans the player for a specified time.
api-version: 1.16
author: InitialPosition
website: www.initialposition.net
commands:
  health:
    description: Shows the player their current health.
    usage: /<command>